-- Create medical research tables in Research_Landing schema
CREATE OR REPLACE TABLE RESEARCH_LANDING.TRIALS (
    TRIAL_ID INT,
    TRIAL_NAME STRING,
    START_DATE DATE,
    END_DATE DATE,
    TRIAL_PHASE STRING,
    MEDICAL_CONDITION STRING
);

CREATE OR REPLACE TABLE RESEARCH_LANDING.TRIALS (
    TRIAL_ID INT,
    TRIAL_NAME STRING,
    START_DATE DATE,
    END_DATE DATE,
    "PHASE" STRING,
    "CONDITION" STRING
);

CREATE OR REPLACE TABLE RESEARCH_LANDING.PARTICIPATION (
    PARTICIPATION_ID INT,
    PATIENT_ID INT,
    TRIAL_ID INT,
    PARTICIPATION_STATUS STRING,
    CONSENT_DATE DATE
);
