-- Create medical research tables in Research_Landing schema
CREATE OR REPLACE TABLE STAGING.PATIENTS (
    PATIENT_ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    DOB DATE,
    GENDER STRING,
    ENROLLMENT_DATE DATE
);

CREATE OR REPLACE TABLE STAGING.TRIALS (
    TRIAL_ID INT,
    TRIAL_NAME STRING,
    START_DATE DATE,
    END_DATE DATE,
    TRIAL_STAGE STRING,
    DIAGNOSIS STRING
);

CREATE OR REPLACE TABLE STAGING.PARTICIPATION (
    PARTICIPATION_ID INT,
    PATIENT_ID INT,
    TRIAL_ID INT,
    PARTICIPATION_STATUS STRING,
    CONSENT_DATE DATE
);
