-- 02_seed_data.sql
-- Seed data into target schema tables from shared S3 stage

COPY INTO ${TARGET_SCHEMA}.PATIENTS
FROM @RESEARCH_LANDING.RESEARCH_S3_STAGE/patients.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

COPY INTO ${TARGET_SCHEMA}.TRIALS
FROM @RESEARCH_LANDING.RESEARCH_S3_STAGE/trials.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

COPY INTO ${TARGET_SCHEMA}.PARTICIPATION
FROM @RESEARCH_LANDING.RESEARCH_S3_STAGE/participation.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
