-- Seed data into Research_Landing schema tables from S3 stage
COPY INTO RESEARCH_LANDING.PATIENTS
FROM @RESEARCH_S3_STAGE/patients.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

COPY INTO RESEARCH_LANDING.TRIALS
FROM @RESEARCH_S3_STAGE/trials.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

COPY INTO RESEARCH_LANDING.PARTICIPATION
FROM @RESEARCH_S3_STAGE/participation.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
