COPY INTO ${TARGET_SCHEMA}.PATIENTS
FROM @RESEARCH_LANDING/patients.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

COPY INTO ${TARGET_SCHEMA}.TRIALS
FROM @RESEARCH_LANDING/trials.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

COPY INTO ${TARGET_SCHEMA}.PARTICIPATION
FROM @RESEARCH_LANDING/participation.csv
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
