-- 03_transform.sql
-- Create a view summarizing patient-trial relationships
CREATE OR REPLACE VIEW ${TARGET_SCHEMA}.PATIENT_TRIAL_SUMMARY AS
SELECT
    P.FIRST_NAME,
    P.LAST_NAME,
    P.GENDER,
    P.DOB,
    T.TRIAL_NAME,
    T.DIAGNOSIS,                -- updated from MEDICAL_CONDITION
    PT.PARTICIPATION_STATUS,
    PT.CONSENT_DATE,
    P.FIRST_NAME || ' ' || P.LAST_NAME AS FULL_NAME
FROM ${TARGET_SCHEMA}.PATIENTS AS P
JOIN ${TARGET_SCHEMA}.PARTICIPATION AS PT
    ON P.PATIENT_ID = PT.PATIENT_ID
JOIN ${TARGET_SCHEMA}.TRIALS AS T
    ON PT.TRIAL_ID = T.TRIAL_ID;
