-- Create a view summarizing patient-trial relationships
CREATE OR REPLACE VIEW RESEARCH_LANDING.PATIENT_TRIAL_SUMMARY AS
SELECT
    P.FIRST_NAME,
    P.LAST_NAME,
    P.GENDER,
    P.DOB,
    T.TRIAL_NAME,
    T.DIAGNOSIS,          -- was MEDICAL_CONDITION
    PT.PARTICIPATION_STATUS,
    PT.CONSENT_DATE,
    P.FIRST_NAME || ' ' || P.LAST_NAME AS FULL_NAME
FROM RESEARCH_LANDING.PATIENTS AS P
JOIN RESEARCH_LANDING.PARTICIPATION AS PT
    ON RESEARCH_LANDING.PATIENTS.PATIENT_ID = RESEARCH_LANDING.PARTICIPATION.PATIENT_ID
JOIN RESEARCH_LANDING.TRIALS AS T
    ON RESEARCH_LANDING.PARTICIPATION.TRIAL_ID = RESEARCH_LANDING.TRIALS.TRIAL_ID;
