-- ✅ Row counts
SELECT 'PATIENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RESEARCH_LANDING.PATIENTS;
SELECT 'TRIALS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RESEARCH_LANDING.TRIALS;
SELECT 'PARTICIPATION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RESEARCH_LANDING.PARTICIPATION;

-- ✅ Referential integrity: PARTICIPATION → PATIENTS
SELECT COUNT(*) AS INVALID_PATIENT_REFS
FROM RESEARCH_LANDING.PARTICIPATION AS PT
LEFT JOIN RESEARCH_LANDING.PATIENTS AS P ON PT.PATIENT_ID = P.PATIENT_ID
WHERE P.PATIENT_ID IS NULL;

-- ✅ Referential integrity: PARTICIPATION → TRIALS
SELECT COUNT(*) AS INVALID_TRIAL_REFS
FROM RESEARCH_LANDING.PARTICIPATION AS PT
LEFT JOIN RESEARCH_LANDING.TRIALS AS T ON PT.TRIAL_ID = T.TRIAL_ID
WHERE T.TRIAL_ID IS NULL;

-- ✅ Null checks in critical fields
SELECT COUNT(*) AS NULL_PATIENT_NAMES
FROM RESEARCH_LANDING.PATIENTS
WHERE FIRST_NAME IS NULL OR LAST_NAME IS NULL;

SELECT COUNT(*) AS NULL_TRIAL_NAMES
FROM RESEARCH_LANDING.TRIALS
WHERE TRIAL_NAME IS NULL;

SELECT COUNT(*) AS NULL_PARTICIPATION_STATUS
FROM RESEARCH_LANDING.PARTICIPATION
WHERE "STATUS" IS NULL;

-- ✅ Optional: Consent date after DOB
SELECT COUNT(*) AS INVALID_CONSENT_DATES
FROM RESEARCH_LANDING.PARTICIPATION AS PT
JOIN RESEARCH_LANDING.PATIENTS AS P ON PT.PATIENT_ID = P.PATIENT_ID
WHERE PT.CONSENT_DATE < P.DOB;
